import type { NextPage } from 'next'
import Head from 'next/head'
import { useAuth0 } from "@auth0/auth0-react";
import styles from '../styles/Home.module.css'
import If from '../components/if'

const Home: NextPage = () => {
  const { user } = useAuth0();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <If condition={!!user}>
          You are logged in
      </If>
    </div>
  )
}

export default Home
